### ISSUE TITLE
Request for assistance: Test package not executing with jest command - Week 2

### ISSUE THREAD

**Issue by RamirezKaren-FS** [jworkman/ASL-Knowledge-Base#10]
# Issue Description -- Unable to Run Tests and call Jest 

Please explain your issue in as much detail as possible here...

I followed along line per line with the lecture and even made sure to install all missing packages before downloading the test package but realized that the node was not 18 so I deleted everything and retried but it did not work. I decided to create a whole new folder to use and installed everything in the exact order as the lecture even waiting for the install of axios and the node-libcurl.  The package installed fine showing it was ready to go but when I ran it nothing happened The terminal showed command not found. 

# Full Error Backtrace
First time trying I had changed the node to the 18 version in my local terminal and assumed it had changed in my work folder which it did not. I thought that was the issue so I created a whole new folder to test out and it still did not work although it shows the package installed. 

# Screenshots
This screenshot is for trying to run jest right after install

<img width="1312" alt="Screenshot 2024-07-09 at 5 12 42 PM" src="https://github.com/jworkman/ASL-Knowledge-Base/assets/148847274/6d3e296a-07c9-4c59-8304-d59fcbf8233c">

this is showing I can call the wdv-cli but only with the npx attached 

<img width="1312" alt="Screenshot 2024-07-09 at 5 16 21 PM" src="https://github.com/jworkman/ASL-Knowledge-Base/assets/148847274/0b5fd5b2-e963-4d06-a048-71562e6925a8">

Any relevant screenshot information goes here. 

# Any Other Notes
Thank you in advance for your help and sorry for any inconvenience.

**Comment by jworkman** [comment]
Hi Karen,

So I think in the lecture video I ran into the "jest not found" issue, but I was able to fix it with the following commands: 

```
npm install -g jest
npm install --save axios
```

**Comment by RamirezKaren-FS** [comment]
I had rewatched the lecture and only saw the issues with not having axios and node-libcurl installed so I guess I passed over the jest issue. I tried it and it worked thank you so much !!!!

**Comment by jworkman** [comment]
Awesome. Closing out this issue.
