### ISSUE TITLE
Request for assistance: Trouble downloading telnet for terminal

### ISSUE THREAD

**Issue by ChalmersSachi-FS** [jworkman/ASL-Knowledge-Base#11]
# Issue Description
i am following along with the live lecture and i am having trouble download telnet into my terminal 
Please explain your issue in as much detail as possible here...
I cannot download telnet in my terminal I am following what is provided on the screen
# Full Error Backtrace

If your having issues with an error or bug that is producing error output. Copy/paste the output of that error here. 

# Screenshots

<img width="1728" alt="Screenshot 2024-08-15 at 3 43 17 PM" src="https://github.com/user-attachments/assets/bb94d164-6623-49f4-a48e-54ec2d058a55">

Any relevant screenshot information goes here. 

# Any Other Notes

Steps on how to reproduce, special context, etc goes here.

**Comment by jworkman** [comment]
Looks like you miss spelled the URL. I see "workam" in the URL when it should be "workman". Your missing the "m".

**Comment by jworkman** [comment]
Additionally you did not specify an output path file. The command should be as follows:

curl -o Dockerfile https://raw.githubusercontent.com/jworkman/telnet/main/Dockerfile

**Comment by ChalmersSachi-FS** [comment]
Okay I will be making the correction right now. Thank you
