### ISSUE TITLE
Request for assistance: HTTP TRIVIA GAME

### ISSUE THREAD

**Issue by ChalmersSachi-FS** [jworkman/ASL-Knowledge-Base#12]
# Issue Description
I am very confused on what to do.
<img width="1728" alt="Screenshot 2024-08-17 at 8 04 11 PM" src="https://github.com/user-attachments/assets/d91be9dc-ab55-459c-a5ed-23af1caf400c">

Please explain your issue in as much detail as possible here...
I am very confused on what has to be done. 
# Full Error Backtrace

If your having issues with an error or bug that is producing error output. Copy/paste the output of that error here. 

# Screenshots

Any relevant screenshot information goes here. 

# Any Other Notes

Steps on how to reproduce, special context, etc goes here.

**Comment by jworkman** [comment]
Okay, I'm not quite sure which part you're confused on. It would help me to know which part you are having trouble understanding. All of the game instructions are all listed in the first curl request data. You need to setup/register a new game session using your email first, then you go through each question using POST requests to the `/game` endpoint. Once you have answered all 5 questions you can hit the `/game/score` endpoint to get your game score results.

**Comment by ChalmersSachi-FS** [comment]
Can I retake this class?

**Comment by jworkman** [comment]
Hi Sachi,

I'm taking this thread offline so that we can talk privately.
