### ISSUE TITLE
Request for assistance: Filter test for week 2 assignment seems incorrect

### ISSUE THREAD

**Issue by MendezCarlos-FS** [jworkman/ASL-Knowledge-Base#4]
# Issue Description

When running the Jest command for week 2's assignment, the filtering portion of the tests do not seem to align properly with the expected results.

# Full Error Backtrace - Img 1

<img width="1018" alt="Screenshot 2024-02-16 at 12 11 26 PM" src="https://github.com/jworkman/ASL-Knowledge-Base/assets/135058688/29f38b01-17e7-4e78-954a-b8d5f5892e4d">

# Screenshots

## Running the failing test command in Terminal with cURL - Img 2
<img width="585" alt="Screenshot 2024-02-16 at 12 11 26 PM copy" src="https://github.com/jworkman/ASL-Knowledge-Base/assets/135058688/04e2c745-36b1-40cc-b016-97f748d8687a">

## Running the failing test command in Terminal with cURL using direction=desc - Img 3
<img width="578" alt="Screenshot 2024-02-16 at 12 22 24 PM" src="https://github.com/jworkman/ASL-Knowledge-Base/assets/135058688/ad4521da-e0dc-4d5f-8d3a-4717078b2d49">

## Running the failing test command in Terminal with cURL using sort=birthday - Img 4
<img width="580" alt="Screenshot 2024-02-16 at 12 24 57 PM" src="https://github.com/jworkman/ASL-Knowledge-Base/assets/135058688/4926eb10-39ef-4017-95b4-56bd77604737">

# Any Other Notes

- Just running the Jest command triggers the test failure. From looking at the data and the test expectations, it seems impossible for the two to be correct. As the default sort is based off of the fname and the default direction is ascending, the result in Img 2 seems like the correct data (William being the first sorted value that meets the filter criteria), but the expected data in the test is from a person name David, whom would be much later in the list.
- Even if the direction were to be set to descending like in Img 3, the first person ends up being Anthony (which makes sense with the default sort value).
- If I use sort=birthday like in Img 4, the expected first test value is the 4th one in the list (highlighted). As a side note, the first value in this result has a different birthday format compared to every other value. Don't know if that's on purpose or not.

**Comment by jworkman** [comment]
So the default ordering should be the ID I think. Since David Parez is the first one in the data array (not fname).
