### ISSUE TITLE
Request for assistance: Issue installing NPM package for star tracker

### ISSUE THREAD

**Issue by MaddaFox** [jworkman/ASL-Knowledge-Base#6]
# Issue Description

When attempting to install the npm package `@jworkman-fs/wdv-cli` I am encounter an error in terminal. Screenshots provied below for reference.

# Screenshots

<img width="1728" alt="Screenshot 2024-02-22 at 11 52 33 AM" src="https://github.com/jworkman/ASL-Knowledge-Base/assets/132394127/29c93e3d-d922-4e01-ac1c-9ac7384231ef">
<img width="1728" alt="Screenshot 2024-02-22 at 11 52 45 AM" src="https://github.com/jworkman/ASL-Knowledge-Base/assets/132394127/c6655374-ffc2-474c-83c8-34c9761287a5">

# Any Other Notes

I did see this [issue](https://github.com/jworkman/ASL-Knowledge-Base/issues/2) on the GitHub repository for the package, but it did not seem to be the same issue I am encountering. Also this issue was running it in the node container. I am running it in a new terminal window on my local machine.

## Steps taken:

1. Open a new terminal application window.
2. Run the command `npm install -g @jworkman-fs/wdv-cli`

**Comment by jworkman** [comment]
So this error seems to happen when students are running NodeJS v20 or higher. Please roll back to the latest v18 LTS. 

```
nvm install v18.19.1
nvm use v18.19.1
nvm alias default v18.19.1
npm install -g @jworkman-fs/wdv-cli
```
