### ISSUE TITLE
Request for assistance: 

### ISSUE THREAD

**Issue by MerrySonoely-FS** [jworkman/ASL-Knowledge-Base#8]
# Issue Description
Restful Routes assignment
Please explain your issue in as much detail as possible here...

# Full Error Backtrace
"
sonoelyrivera@Elys-MacBook-Pro asl_restful_routes % jest
 FAIL  ./contacts.test.js
  ● Test suite failed to run

    The module '/Users/sonoelyrivera/node_modules/node-libcurl/lib/binding/node_libcurl.node'
    was compiled against a different Node.js version using
    NODE_MODULE_VERSION 108. This version of Node.js requires
    NODE_MODULE_VERSION 115. Please try re-compiling or re-installing
    the module (for instance, using `npm rebuild` or `npm install`).

       9 | } = require('@jworkman-fs/asl/src/Exception/testing.js')
      10 | const { InvalidContactSchemaError } = require('@jworkman-fs/asl/src/Exception/index.js')
    > 11 | const { Curl } = require('node-libcurl')
         |                  ^
      12 |
      13 | const tests = {
      14 |   groups: [

      at Runtime._loadModule (../../.nvm/versions/node/v20.11.0/lib/node_modules/jest/node_modules/jest-runtime/build/index.js:1018:29)
      at Object.<anonymous> (../../node_modules/node-libcurl/lib/Easy.ts:10:44)
      at Object.<anonymous> (../../node_modules/node-libcurl/lib/Curl.ts:22:1)
      at Object.<anonymous> (../../node_modules/node-libcurl/lib/index.ts:11:1)
      at Object.require (contacts.test.js:11:18)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.18 s
Ran all test suites.
"
# Screenshots

<img width="1246" alt="Screenshot 2024-04-27 at 2 45 39 PM" src="https://github.com/jworkman/ASL-Knowledge-Base/assets/137943977/3138011e-13a2-4112-85e9-0b0807723923">
 

# Any Other Notes

I ran Jest in the command, but the test failed to run. I researched for hours how to fix this and didn't come across a clear solution.

**Comment by jworkman** [comment]
This issue is directly related to another issue that was solved in issue number: #6. The solution is to install NodeJS v18. Please read the last comment on that thread to fix the issue.

**Comment by MerrySonoely-FS** [comment]
Okay, thank you so much.
