### ISSUE TITLE
Request for assistance: Mysql error in wk3 assignment.

### ISSUE THREAD

**Issue by MerrySonoely-FS** [jworkman/ASL-Knowledge-Base#9]
# Issue Description

Hello I've been having issues with commanding mysql2 in the week 3 assignment. Every time I try to use the command: 'mysql -uroot', I get an error: 'ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)'. Previous to that I was getting an error 'command not found: mysql'. I had done some research online and changed the socket, hoping it would resolve the original command issue. Now I can't seem to find a solution to revert the socket back. I apologize if this is confusing. I've also tried uninstalling and reinstalling mysql2 to my project, mysql desktop, and even installed mysql-server to my project.

# Full Error Backtrace

'ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)'.

# Screenshots

![image](https://github.com/jworkman/ASL-Knowledge-Base/assets/137943977/30671e97-c655-4b88-b8f9-76d88c82de59)

# Any Other Notes
n/a

**Comment by jworkman** [comment]
Hi Sonoely,

Sorry, not sure why I didn't see the email notification for this, but does the error say "mysql2" module not found, or is it something else? I see your screenshot, but its cropped off at the top of the back trace message so I can't see the full error message (or at least not the most important line which is always the first couple of lines).
